conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
provider:
  linux_ppc64le: default
  linux_aarch64: default
  osx_arm64: default